In [1]:
#Import dependencies
import pandas as pd
from sqlalchemy import create_engine
from config import SQL_key

In [2]:
# Read csv file
path_intake="raw_data/Austin_Animal_Center_Intakes.csv"
path_outcome="raw_data/Austin_Animal_Center_Outcomes.csv"

In [3]:
animal_outcome=pd.read_csv(path_outcome)
animal_outcome.head()

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
0,A794011,Chunk,05/08/2019 06:20:00 PM,05/08/2019 06:20:00 PM,05/02/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White
1,A776359,Gizmo,07/18/2018 04:02:00 PM,07/18/2018 04:02:00 PM,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown
2,A720371,Moose,02/13/2016 05:59:00 PM,02/13/2016 05:59:00 PM,10/08/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff
3,A674754,NaN,03/18/2014 11:47:00 AM,03/18/2014 11:47:00 AM,03/12/2014,Transfer,Partner,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby
4,A689724,*Donatello,10/18/2014 06:52:00 PM,10/18/2014 06:52:00 PM,08/01/2014,Adoption,NaN,Cat,Neutered Male,2 months,Domestic Shorthair Mix,Black

In [4]:
# drop columns
animal_outcome_df=animal_outcome.drop(columns=['Outcome Subtype','MonthYear'])
animal_outcome_df.head()

,Animal ID,Name,DateTime,Date of Birth,Outcome Type,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
0,A794011,Chunk,05/08/2019 06:20:00 PM,05/02/2017,Rto-Adopt,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White
1,A776359,Gizmo,07/18/2018 04:02:00 PM,07/12/2017,Adoption,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown
2,A720371,Moose,02/13/2016 05:59:00 PM,10/08/2015,Adoption,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff
3,A674754,NaN,03/18/2014 11:47:00 AM,03/12/2014,Transfer,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby
4,A689724,*Donatello,10/18/2014 06:52:00 PM,08/01/2014,Adoption,Cat,Neutered Male,2 months,Domestic Shorthair Mix,Black

In [5]:
# load file
animal_intake=pd.read_csv(path_intake)
animal_intake.head()

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A786884,*Brock,01/03/2019 04:19:00 PM,01/03/2019 04:19:00 PM,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,07/05/2015 12:59:00 PM,07/05/2015 12:59:00 PM,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,04/14/2016 06:43:00 PM,04/14/2016 06:43:00 PM,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White
3,A665644,NaN,10/21/2013 07:59:00 AM,10/21/2013 07:59:00 AM,Austin (TX),Stray,Sick,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico
4,A682524,Rio,06/29/2014 10:38:00 AM,06/29/2014 10:38:00 AM,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray

In [6]:
#drop columns
animal_intake_df=animal_intake.drop(columns=['Found Location','MonthYear','Breed','Color','Name','Intake Condition','Animal Type',"Sex upon Intake"])
animal_intake_df.head()

  Animal ID                DateTime Intake Type Age upon Intake
0   A786884  01/03/2019 04:19:00 PM       Stray         2 years
1   A706918  07/05/2015 12:59:00 PM       Stray         8 years
2   A724273  04/14/2016 06:43:00 PM       Stray       11 months
3   A665644  10/21/2013 07:59:00 AM       Stray         4 weeks
4   A682524  06/29/2014 10:38:00 AM       Stray         4 years

In [7]:
# merge two csv
combined=pd.merge(animal_outcome_df,animal_intake_df,on="Animal ID",how="left")
combined.head()

,Animal ID,Name,DateTime_x,Date of Birth,Outcome Type,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color,DateTime_y,Intake Type,Age upon Intake
0,A794011,Chunk,05/08/2019 06:20:00 PM,05/02/2017,Rto-Adopt,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White,05/02/2019 04:51:00 PM,Owner Surrender,2 years
1,A776359,Gizmo,07/18/2018 04:02:00 PM,07/12/2017,Adoption,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown,07/12/2018 12:46:00 PM,Stray,1 year
2,A720371,Moose,02/13/2016 05:59:00 PM,10/08/2015,Adoption,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff,02/08/2016 11:05:00 AM,Stray,4 months
3,A720371,Moose,02/13/2016 05:59:00 PM,10/08/2015,Adoption,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff,02/15/2016 10:37:00 AM,Owner Surrender,4 months
4,A674754,NaN,03/18/2014 11:47:00 AM,03/12/2014,Transfer,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby,03/18/2014 07:11:00 AM,Stray,6 days

In [8]:
#rename columns and sort by date
combined_df=combined.rename(columns={
    "DateTime_x": "DateTime_Outcome", "DateTime_y": "DateTime_Intake","Animal ID":"Animal_ID",
    "Date of Birth":"Date_of_Birth","Outcome Type":"Outcome_Type","Animal Type":"Animal_Type",
    "Sex upon Outcome":"Sex_upon_Outcome","Age upon Outcome":"Age_upon_Outcome",
    "Intake Type":"Intake_Type","Age upon Intake":"Age_upon_Intake"

})
combined_df=combined_df.sort_values(by='Animal_ID',ascending=False)
combined_df.head()

,Animal_ID,Name,DateTime_Outcome,Date_of_Birth,Outcome_Type,Animal_Type,Sex_upon_Outcome,Age_upon_Outcome,Breed,Color,DateTime_Intake,Intake_Type,Age_upon_Intake
152748,A818085,Harlequin,06/01/2020 06:19:00 PM,04/16/2020,Transfer,Dog,Intact Female,1 month,Pit Bull Mix,Black/White,06/01/2020 01:15:00 PM,Owner Surrender,1 month
152734,A818074,NaN,06/01/2020 01:19:00 PM,05/10/2020,Transfer,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby/White,06/01/2020 12:09:00 PM,Stray,3 weeks
152739,A818073,NaN,06/01/2020 01:18:00 PM,05/10/2020,Transfer,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby/White,06/01/2020 12:09:00 PM,Stray,3 weeks
152735,A818072,NaN,06/01/2020 01:18:00 PM,05/10/2020,Transfer,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Black Smoke,06/01/2020 12:09:00 PM,Stray,3 weeks
152738,A818071,NaN,06/01/2020 01:17:00 PM,05/10/2020,Transfer,Cat,Intact Female,3 weeks,Domestic Shorthair Mix,Calico,06/01/2020 12:09:00 PM,Stray,3 weeks

In [9]:
# duplicated columns
combined_df=combined_df.drop_duplicates(subset='Animal_ID', keep='first')
# only keep Dogs and Cats
combined_df=combined_df[(combined_df['Animal_Type']=='Dog')|(combined_df['Animal_Type']=='Cat')]

In [10]:
combined_df.head()

,Animal_ID,Name,DateTime_Outcome,Date_of_Birth,Outcome_Type,Animal_Type,Sex_upon_Outcome,Age_upon_Outcome,Breed,Color,DateTime_Intake,Intake_Type,Age_upon_Intake
152748,A818085,Harlequin,06/01/2020 06:19:00 PM,04/16/2020,Transfer,Dog,Intact Female,1 month,Pit Bull Mix,Black/White,06/01/2020 01:15:00 PM,Owner Surrender,1 month
152734,A818074,NaN,06/01/2020 01:19:00 PM,05/10/2020,Transfer,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby/White,06/01/2020 12:09:00 PM,Stray,3 weeks
152739,A818073,NaN,06/01/2020 01:18:00 PM,05/10/2020,Transfer,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby/White,06/01/2020 12:09:00 PM,Stray,3 weeks
152735,A818072,NaN,06/01/2020 01:18:00 PM,05/10/2020,Transfer,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Black Smoke,06/01/2020 12:09:00 PM,Stray,3 weeks
152738,A818071,NaN,06/01/2020 01:17:00 PM,05/10/2020,Transfer,Cat,Intact Female,3 weeks,Domestic Shorthair Mix,Calico,06/01/2020 12:09:00 PM,Stray,3 weeks

In [11]:
# Combined mix 
combined_df["Breed"]=combined_df["Breed"].str.replace("/",' Mix /')
combined_df["Breed"]=combined_df["Breed"].str.partition("/")
combined_df.head(40)

,Animal_ID,Name,DateTime_Outcome,Date_of_Birth,Outcome_Type,Animal_Type,Sex_upon_Outcome,Age_upon_Outcome,Breed,Color,DateTime_Intake,Intake_Type,Age_upon_Intake
152748,A818085,Harlequin,06/01/2020 06:19:00 PM,04/16/2020,Transfer,Dog,Intact Female,1 month,Pit Bull Mix,Black/White,06/01/2020 01:15:00 PM,Owner Surrender,1 month
152734,A818074,NaN,06/01/2020 01:19:00 PM,05/10/2020,Transfer,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby/White,06/01/2020 12:09:00 PM,Stray,3 weeks
152739,A818073,NaN,06/01/2020 01:18:00 PM,05/10/2020,Transfer,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby/White,06/01/2020 12:09:00 PM,Stray,3 weeks
152735,A818072,NaN,06/01/2020 01:18:00 PM,05/10/2020,Transfer,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Black Smoke,06/01/2020 12:09:00 PM,Stray,3 weeks
152738,A818071,NaN,06/01/2020 01:17:00 PM,05/10/2020,Transfer,Cat,Intact Female,3 weeks,Domestic Shorthair Mix,Calico,06/01/2020 12:09:00 PM,Stray,3 weeks
152732,A818068,NaN,06/01/2020 01:17:00 PM,05/13/2020,Transfer,Cat,Intact Male,2 weeks,Domestic Shorthair,Cream Tabby/White,06/01/2020 11:54:00 AM,Stray,2 weeks
152737,A818050,NaN,06/01/2020 01:25:00 PM,06/01/2018,Return to Owner,Dog,Intact Female,2 years,Pug,Brown/Fawn,06/01/2020 09:23:00 AM,Stray,2 years
152733,A818049,NaN,06/01/2020 01:24:00 PM,06/01/2018,Return to Owner,Dog,Intact Female,2 years,Pit Bull,White/Gray,06/01/2020 09:23:00 AM,Stray,2 years
152715,A818037,NaN,05/31/2020 05:55:00 PM,04/19/2020,Return to Owner,Dog,Intact Female,1 month,Labrador Retriever Mix,Black/Tricolor,05/31/2020 04:49:00 PM,Public Assist,1 month
152747,A818029,Blue,06/01/2020 05:44:00 PM,05/31/2014,Return to Owner,Dog,Spayed Female,6 years,Labrador Retriever,Black,05/30/2020 07:30:00 AM,Stray,6 years
152705,A818015,NaN,05/30/2020 04:50:00 PM,05/28/2020,Transfer,Cat,Unknown,2 days,Domestic Shorthair,Orange Tabby,05/30/2020 02:58:00 PM,Stray,2 days
152704,A818014,NaN,05/30/2020 04:50:00 PM,05/28/2020,Transfer,Cat,Unknown,2 days,Domestic Shorthair,Orange Tabby/White,05/30/2020 02:58:00 PM,Stray,2 days
152713,A818013,*Smokey,05/31/2020 03:46:00 PM,05/30/2018,Transfer,Cat,Neutered Male,2 years,Domestic Longhair,Black,05/30/2020 02:16:00 PM,Stray,2 years
152736,A818002,Piper,06/01/2020 01:57:00 PM,05/30/2018,Return to Owner,Dog,Intact Female,2 years,Vizsla,Brown,05/30/2020 09:57:00 AM,Stray,2 years
152706,A818001,Swis,05/30/2020 05:04:00 PM,05/30/2018,Return to Owner,Dog,Spayed Female,2 years,German Shepherd Mix,Brown/Black,05/30/2020 09:44:00 AM,Stray,2 years
152685,A817992,NaN,05/30/2020 08:57:00 AM,05/20/2020,Disposal,Cat,Intact Female,1 weeks,Domestic Shorthair,White/Black,05/30/2020 07:44:00 AM,Stray,1 weeks
152687,A817991,NaN,05/30/2020 08:54:00 AM,03/30/2020,Disposal,Dog,Intact Male,1 month,Yorkshire Terrier Mix,Silver,05/30/2020 07:40:00 AM,Stray,1 month
152693,A817990,NaN,05/30/2020 08:54:00 AM,05/30/2018,Disposal,Dog,Unknown,2 years,Chihuahua Shorthair,Tan,05/30/2020 07:44:00 AM,Stray,2 years
152694,A817989,NaN,05/30/2020 08:56:00 AM,03/01/2020,Disposal,Cat,Unknown,2 months,Domestic Shorthair,Blue,05/30/2020 07:40:00 AM,Stray,2 months
152686,A817988,NaN,05/30/2020 08:56:00 AM,05/10/2020,Disposal,Cat,Intact Female,2 weeks,Domestic Shorthair,White,05/30/2020 07:44:00 AM,Stray,2 weeks
152683,A817987,NaN,05/30/2020 08:55:00 AM,05/30/2018,Disposal,Cat,Unknown,2 years,Domestic Shorthair,Brown Tabby,05/30/2020 07:40:00 AM,Stray,2 years
152684,A817986,NaN,05/30/2020 08:55:00 AM,05/20/2020,Disposal,Cat,Intact Female,1 weeks,Domestic Shorthair,Orange,05/30/2020 07:44:00 AM,Stray,1 weeks
152697,A817956,Brownie,05/30/2020 11:08:00 AM,05/29/2018,Return to Owner,Dog,Intact Male,2 years,Labrador Retriever Mix,Tan,05/29/2020 02:26:00 PM,Stray,2 years
152674,A817925,Blue,05/29/2020 01:58:00 PM,05/29/2018,Return to Owner,Dog,Intact Female,2 years,Pit Bull,Blue,05/29/2020 09:02:00 AM,Stray,2 years
152679,A817923,Ellie,05/29/2020 01:59:00 PM,05/29/2017,Return to Owner,Dog,Intact Female,3 years,Pit Bull,White,05/29/2020 08:34:00 AM,Stray,3 years
152663,A817894,NaN,05/28/2020 01:23:00 PM,05/26/2020,Transfer,Cat,Intact Female,2 days,Domestic Shorthair,Blue,05/28/2020 11:10:00 AM,Stray,2 days
152707,A817873,Shae,05/30/2020 05:17:00 PM,08/01/2017,Return to Owner,Dog,Intact Female,2 years,German Shepherd,Brown/Black,05/27/2020 06:45:00 PM,Abandoned,2 years
152653,A817868,NaN,05/27/2020 07:17:00 AM,05/12/2020,Transfer,Cat,Intact Male,2 weeks,Domestic Shorthair,Orange Tabby/White,05/27/2020 03:18:00 PM,Stray,2 weeks
152655,A817867,NaN,05/27/2020 07:16:00 AM,05/12/2020,Transfer,Cat,Intact Male,2 weeks,Domestic Shorthair,Cream Tabby,05/27/2020 03:18:00 PM,Stray,2 weeks
152651,A817866,NaN,05/27/2020 07:16:00 AM,05/12/2020,Transfer,Cat,Intact Male,2 weeks,Domestic Shorthair,Blue Tabby,05/27/2020 03:18:00 PM,Stray,2 weeks
152654,A817865,NaN,05/27/2020 07:16:00 AM,05/12/2020,Transfer,Cat,Intact Male,2 weeks,Domestic Shorthair,Blue Tabby,05/27/2020 03:18:00 PM,Stray,2 weeks
152657,A817860,NaN,05/28/2020 11:14:00 AM,04/05/2020,Transfer,Cat,Intact Male,1 month,Domestic Longhair,Orange Tabby,05/27/2020 02:48:00 PM,Stray,1 month
152643,A817858,Ritchie,05/27/2020 04:47:00 PM,11/01/2018,Return to Owner,Dog,Intact Male,1 year,Australian Cattle Dog,Tricolor/Black,05/27/2020 02:15:00 PM,Stray,1 year
152652,A817853,NaN,05/27/2020 07:15:00 AM,05/13/2020,Transfer,Cat,Intact Male,2 weeks,Domestic Shorthair,Gray,05/27/2020 01:53:00 PM,Stray,2 weeks
152625,A817847,NaN,05/27/2020 11:18:00 AM,04/27/2020,Transfer,Cat,Intact Female,4 weeks,Domestic Shorthair,Blue Tabby/White,05/27/2020 11:16:00 AM,Stray,4 weeks
152708,A817831,NaN,05/27/2020 02:32:00 PM,05/27/2018,Transfer,Dog,Intact Male,2 years,Cairn Terrier,Black/Brown,05/27/2020 08:25:00 AM,Stray,2 years
152744,A817802,NaN,06/01/2020 03:26:00 PM,05/26/2019,Transfer,Dog,Neutered Male,1 year,Dachshund Mix,Black,05/26/2020 03:09:00 PM,Stray,1 year
152617,A817791,Sissy,05/27/2020 09:54:00 AM,02/26/2020,Transfer,Dog,Intact Female,2 months,Labrador Retriever Mix,Black,05/26/2020 01:31:00 PM,Owner Surrender,2 months
152672,A817778,Blue,05/29/2020 11:10:00 AM,05/26/2014,Return to Owner,Dog,Neutered Male,6 years,Labrador Retriever,Brown,05/26/2020 10:52:00 AM,Stray,6 years
152584,A817770,Smokey,05/26/2020 11:37:00 AM,03/26/2020,Transfer,Dog,Intact Male,1 month,Pit Bull,Blue,05/26/2020 08:48:00 AM,Owner Surrender,1 month

In [12]:
# Push transformed CSV file to folder
combined_df.to_csv("Animals.csv", index=False, header=True)

In [13]:
# Create Postgress connection
rds_connection_string = f'postgres:{SQL_key}@localhost:5432/animals_db'
engine = create_engine(f'postgresql://{rds_connection_string}')

In [14]:
# View tables
engine.table_names()

['austin_animals']

In [15]:
# Push transformed file to Postgres
combined_df.to_sql(name="austin_animals", con=engine, if_exists='append', index=False)

In [16]:
# Query file from Postgres
pd.read_sql_query('select * from austin_Animals', con=engine).head()

,Animal_ID,Name,DateTime_Outcome,Date_of_Birth,Outcome_Type,Animal_Type,Sex_upon_Outcome,Age_upon_Outcome,Breed,Color,DateTime_Intake,Intake_Type,Age_upon_Intake
0,A818085,Harlequin,2020-06-01,2020-04-16,Transfer,Dog,Intact Female,1 month,Pit Bull Mix,Black/White,2020-06-01,Owner Surrender,1 month
1,A818074,None,2020-06-01,2020-05-10,Transfer,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby/White,2020-06-01,Stray,3 weeks
2,A818073,None,2020-06-01,2020-05-10,Transfer,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby/White,2020-06-01,Stray,3 weeks
3,A818072,None,2020-06-01,2020-05-10,Transfer,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Black Smoke,2020-06-01,Stray,3 weeks
4,A818071,None,2020-06-01,2020-05-10,Transfer,Cat,Intact Female,3 weeks,Domestic Shorthair Mix,Calico,2020-06-01,Stray,3 weeks